# Generated by Django 4.2.1 on 2023-05-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nickelodeon', '0002_alter_cartoonuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoonuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
