name: Run Linter adn Tests
on: [ push, pull_request ]
jobs:
  execute_linter_and_tests:
    name: Install requirements and execute linter, and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Install Requirements
        run: pip install flake8 pytest django pytest-django
      - name: Execute flake8 linter
        run: flake8 dj_pro/cartoon --config dj_pro/cartoon/.flake8
      - name: Execute Pytests
        env:
          DJANGO_SETTINGS_MODULE: cartoon.settings
        run: pytest dj_pro/cartoon